name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    - name: Install nightly rust
      run: rustup default nightly
    - name: Install Toolchain
      run: rustup target add wasm32-unknown-unknown --toolchain nightly  
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
